Repository JesusFilm/Ark, pull requests merged in 2021-06, with the labels that each got.

#2 ARK-4 post card
  .bitmap
  package.json
  pnpm-lock.yaml
  src/elements/post-card/index.ts
  src/elements/post-card/post-card.composition.tsx
  src/elements/post-card/post-card.docs.mdx
  src/elements/post-card/post-card.spec.tsx
  src/elements/post-card/post-card.tsx
  src/elements/post-card/variants/default/default.spec.tsx
  src/elements/post-card/variants/default/default.tsx
  src/elements/post-card/variants/default/index.ts
  src/elements/post-card/variants/hero/hero.spec.tsx
  src/elements/post-card/variants/hero/hero.tsx
  src/elements/post-card/variants/hero/index.ts
  src/elements/post-card/variants/index.ts
  src/elements/post-card/variants/item/index.ts
  src/elements/post-card/variants/item/item.spec.tsx
  src/elements/post-card/variants/item/item.tsx
  src/elements/post-card/variants/premiere/index.ts
  src/elements/post-card/variants/premiere/premiere.spec.tsx
  src/elements/post-card/variants/premiere/premiere.tsx
  src/elements/post-card/variants/quote/index.ts
  src/elements/post-card/variants/quote/quote.spec.tsx
  src/elements/post-card/variants/quote/quote.tsx
  src/elements/time-ago/index.ts
  src/elements/time-ago/time-ago.composition.tsx
  src/elements/time-ago/time-ago.docs.mdx
  src/elements/time-ago/time-ago.spec.tsx
  src/elements/time-ago/time-ago.tsx
Labels: new-component

#21 add paper and container to footer
  src/elements/footer/footer.composition.tsx
  src/elements/footer/footer.tsx
Labels: bug

#22 ARK-27 add post header component
  .bitmap
  package.json
  pnpm-lock.yaml
  src/elements/post-header/index.ts
  src/elements/post-header/post-header.composition.tsx
  src/elements/post-header/post-header.docs.mdx
  src/elements/post-header/post-header.spec.tsx
  src/elements/post-header/post-header.tsx
  src/envs/react/jest/jest.config.js
  src/providers/i18n-provider/i18n.spec.ts
  src/providers/i18n-provider/i18n.ts
Labels: enhancement

#26 bump i18n provider version
  .bitmap
Labels: bug

#27 add core components
  .bitmap
  README.md
  src/elements/core/core.docs.mdx
  src/elements/core/core.spec.tsx
  src/elements/core/index.ts
  src/elements/post-card/index.ts
  src/providers/core/core.docs.mdx
  src/providers/core/core.spec.tsx
  src/providers/core/index.ts
Labels: new-component
