Repository JesusFilm/Ark, pull requests merged in 2021-07, with the labels that each got.

#29 update core
  .bitmap
  src/elements/core/index.ts
Labels: bug

#30 use typename instead of name
  .bitmap
  src/elements/block/block.spec.tsx
  src/elements/block/block.tsx
  src/elements/block/blockData.ts
  src/elements/block/core-gallery/core-gallery.composition.tsx
  src/elements/block/core-gallery/core-gallery.spec.tsx
  src/elements/block/core-gallery/core-gallery.tsx
  src/elements/block/core-heading/core-heading.composition.tsx
  src/elements/block/core-heading/core-heading.spec.tsx
  src/elements/block/core-heading/core-heading.tsx
  src/elements/block/core-image/core-image.composition.tsx
  src/elements/block/core-image/core-image.spec.tsx
  src/elements/block/core-image/core-image.tsx
  src/elements/block/core-list/core-list.composition.tsx
  src/elements/block/core-list/core-list.spec.tsx
  src/elements/block/core-list/core-list.tsx
  src/elements/block/core-paragraph/core-paragraph.composition.tsx
  src/elements/block/core-paragraph/core-paragraph.spec.tsx
  src/elements/block/core-paragraph/core-paragraph.tsx
  src/elements/post/postData.ts
Labels: bug

#28 ARK-33 Core Quote Component
  .bitmap
  src/elements/author-card/author-card.tsx
  src/elements/block/block.spec.tsx
  src/elements/block/block.tsx
  src/elements/block/blockData.ts
  src/elements/block/core-heading/core-heading.tsx
  src/elements/block/core-image/core-image.tsx
  src/elements/block/core-list/core-list.tsx
  src/elements/block/core-paragraph/core-paragraph.tsx
  src/elements/block/core-quote/core-quote.composition.tsx
  src/elements/block/core-quote/core-quote.spec.tsx
  src/elements/block/core-quote/core-quote.tsx
  src/elements/block/core-quote/index.ts
  src/elements/post/post.tsx
  src/elements/post/postData.ts
Labels: new-component

#32 ARK-39 Core Embed Component
  .bitmap
  src/elements/block/block.docs.mdx
  src/elements/block/block.spec.tsx
  src/elements/block/block.tsx
  src/elements/block/blockData.ts
  src/elements/block/core-embed/core-embed.composition.tsx
  src/elements/block/core-embed/core-embed.spec.tsx
  src/elements/block/core-embed/core-embed.tsx
  src/elements/block/core-embed/embed/iframe/iframe.spec.tsx
  src/elements/block/core-embed/embed/iframe/iframe.tsx
  src/elements/block/core-embed/embed/iframe/index.ts
  src/elements/block/core-embed/embed/vimeo/index.ts
  src/elements/block/core-embed/embed/vimeo/vimeo.spec.tsx
  src/elements/block/core-embed/embed/vimeo/vimeo.tsx
  src/elements/block/core-embed/embed/youtube/index.ts
  src/elements/block/core-embed/embed/youtube/youtube.spec.tsx
  src/elements/block/core-embed/embed/youtube/youtube.tsx
  src/elements/block/core-embed/index.ts
  src/elements/block/core-paragraph/core-paragraph.spec.tsx
  src/elements/block/error/error.spec.tsx
  src/elements/block/error/error.tsx
  src/elements/block/error/index.ts
  src/elements/post-card/variants/default/default.tsx
  src/elements/post/post.docs.mdx
  src/elements/post/post.tsx
  src/elements/post/postData.ts
Labels: new-component

#37 ARK-47 update post-card component
  .bitmap
  src/elements/post-card/post-card.composition.tsx
  src/elements/post-card/post-card.spec.tsx
  src/elements/post-card/variants/default/default.composition.tsx
  src/elements/post-card/variants/default/default.spec.tsx
  src/elements/post-card/variants/default/default.tsx
  src/elements/post-card/variants/hero/hero.composition.tsx
  src/elements/post-card/variants/hero/hero.spec.tsx
  src/elements/post-card/variants/hero/hero.tsx
  src/elements/post-card/variants/item/item.composition.tsx
  src/elements/post-card/variants/item/item.spec.tsx
  src/elements/post-card/variants/item/item.tsx
  src/elements/post-card/variants/premiere/premiere.composition.tsx
  src/elements/post-card/variants/premiere/premiere.spec.tsx
  src/elements/post-card/variants/premiere/premiere.tsx
  src/elements/post-card/variants/quote/quote.composition.tsx
  src/elements/post-card/variants/quote/quote.spec.tsx
  src/elements/post-card/variants/quote/quote.tsx
  src/elements/post/post.tsx
  src/providers/jesus-film-theme-provider/jesus-film-theme-provider.tsx
  src/providers/jesus-film-theme-provider/theme.ts
Labels: enhancement

#42 ARK-42 Core Arclight Component
  src/elements/block/block.spec.tsx
  src/elements/block/block.tsx
  src/elements/block/blockData.ts
  src/elements/block/core-arclight/core-arclight.composition.tsx
  src/elements/block/core-arclight/core-arclight.spec.tsx
  src/elements/block/core-arclight/core-arclight.tsx
  src/elements/block/core-arclight/index.ts
  src/elements/post/postData.ts
Labels: new-component

#39 ARK-45 Elements Mission
  .bitmap
  src/elements/core/index.ts
  src/elements/mission/index.ts
  src/elements/mission/mission.composition.tsx
  src/elements/mission/mission.docs.mdx
  src/elements/mission/mission.spec.tsx
  src/elements/mission/mission.tsx
Labels: new-component

#43 update block types
  .bitmap
  src/elements/block/block.tsx
Labels: bug

#44 Fix console warnings in test
  .bitmap
  src/compounds/post-list/post-list.spec.tsx
  src/elements/block/block.tsx
  src/elements/block/core-arclight/index.ts
  src/elements/block/core-embed/core-embed.spec.tsx
  src/elements/block/core-embed/core-embed.tsx
  src/elements/block/core-embed/embed/iframe/iframe.spec.tsx
  src/elements/block/core-embed/embed/iframe/iframe.tsx
  src/elements/block/core-embed/embed/iframe/index.ts
  src/elements/block/core-embed/embed/vimeo/index.ts
  src/elements/block/core-embed/embed/vimeo/vimeo.spec.tsx
  src/elements/block/core-embed/embed/vimeo/vimeo.tsx
  src/elements/block/core-embed/embed/youtube/index.ts
  src/elements/block/core-embed/embed/youtube/youtube.spec.tsx
  src/elements/block/core-embed/embed/youtube/youtube.tsx
  src/elements/block/core-gallery/core-gallery.spec.tsx
  src/elements/block/core-gallery/core-gallery.tsx
  src/elements/block/core-heading/core-heading.tsx
  src/elements/block/core-image/core-image.spec.tsx
  src/elements/block/core-image/core-image.tsx
  src/elements/block/core-paragraph/core-paragraph.spec.tsx
  src/elements/block/core-paragraph/core-paragraph.tsx
  src/elements/block/core-quote/core-quote.spec.tsx
  src/elements/block/core-quote/core-quote.tsx
  src/elements/block/lazyblock-arclight/index.ts
  src/elements/block/lazyblock-arclight/lazyblock-arclight.composition.tsx
  src/elements/block/lazyblock-arclight/lazyblock-arclight.spec.tsx
  src/elements/block/lazyblock-arclight/lazyblock-arclight.tsx
  src/elements/mission/mission.spec.tsx
  src/elements/post-card/post-card.spec.tsx
  src/elements/post-card/variants/hero/hero.spec.tsx
  src/elements/post-card/variants/quote/quote.spec.tsx
Labels: bug

#34 ARK-28 Post Footer Component
  .bitmap
  src/elements/post/footer/footer.composition.tsx
  src/elements/post/footer/footer.spec.tsx
  src/elements/post/footer/footer.tsx
  src/elements/post/footer/index.ts
  src/elements/post/post.composition.tsx
  src/elements/post/post.docs.mdx
  src/elements/post/post.tsx
  src/elements/post/postData.ts
Labels: new-component

#41 ARK-44 List Header and ARK-43 Author List
  .bitmap
  src/compounds/author-list/author-list.composition.tsx
  src/compounds/author-list/author-list.docs.mdx
  src/compounds/author-list/author-list.spec.tsx
  src/compounds/author-list/author-list.tsx
  src/compounds/author-list/index.ts
  src/elements/author-card/author-card.composition.tsx
  src/elements/author-card/author-card.docs.mdx
  src/elements/author-card/author-card.spec.tsx
  src/elements/author-card/author-card.tsx
  src/elements/author-card/index.ts
  src/elements/author-list/author-list.composition.tsx
  src/elements/author-list/author-list.docs.mdx
  src/elements/author-list/author-list.spec.tsx
  src/elements/author-list/author-list.tsx
  src/elements/core/index.ts
  src/elements/list-header/index.ts
  src/elements/list-header/list-header.composition.tsx
  src/elements/list-header/list-header.docs.mdx
  src/elements/list-header/list-header.spec.tsx
  src/elements/list-header/list-header.tsx
Labels: new-component
